[build]
  # Build command - runs the obfuscation
  command = "npm install && npm run build"
  
  # Publish directory - where obfuscated files are
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers (optional but recommended)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"